package it.unipi.moviesBloomFilters.job2;

import it.unipi.moviesBloomFilters.BitPosition;
import it.unipi.moviesBloomFilters.BloomFilter;
import org.apache.hadoop.io.IntWritable;
import org.apache.hadoop.mapreduce.Reducer;

import java.io.IOException;
import java.util.BitSet;

// The reducer receives all the BitPosition objects generated by the mappers
// and uses this structure to create the final bloom filter related to a specific rating.

public class BloomFilterGenerationReducerIndexes extends Reducer<IntWritable, BitPosition, IntWritable, BloomFilter> {
    BloomFilter bf = new BloomFilter();

    @Override
    public void reduce(IntWritable rating, Iterable<BitPosition> bits, Context context) throws IOException, InterruptedException {
        int m = context.getConfiguration().getInt("bf." + (rating.get() - 1) + ".parameter.m", 0);
        int k = context.getConfiguration().getInt("bf." + (rating.get() - 1) + ".parameter.k", 0);

        if (m == 0 || k == 0)
            return;

        BitSet bitSet = new BitSet(m);
        for (BitPosition bitPos: bits) {
            for (int i = 0; i < bitPos.getPos().length; i++)
                bitSet.set(bitPos.getPos()[i], true);
        }

        if(!bitSet.isEmpty()) {
            bf.reset(m, k);
            bf.setBits(bitSet);
            context.write(rating, bf);
        }
    }
}
